### ISSUE TITLE
RuntimeError: Dynamo is not supported on Python 3.12+

### ISSUE THREAD

**Issue by hicaoc** [yuhaolove/ChatTTS-WebUI#9]
Traceback (most recent call last):
  File "C:\Users\caoc\AI\ChatTTS-WebUI\webui\main.py", line 39, in <module>
    chat.load_models()
  File "C:\Users\caoc\AI\ChatTTS-WebUI\ChatTTS\ChatTTS\core.py", line 61, in load_models
    self._load(**{k: os.path.join(download_path, v) for k, v in OmegaConf.load(os.path.join(download_path, 'config', 'path.yaml')).items()}, **kwargs)
  File "C:\Users\caoc\AI\ChatTTS-WebUI\ChatTTS\ChatTTS\core.py", line 102, in _load
    gpt.gpt.forward = torch.compile(gpt.gpt.forward,  backend='inductor', dynamic=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caoc\miniconda3\envs\chattts_webui\Lib\site-packages\torch\__init__.py", line 1866, in compile
    raise RuntimeError("Dynamo is not supported on Python 3.12+")
RuntimeError: Dynamo is not supported on Python 3.12+

**Comment by tjw2469** [comment]
encountered the same issue, waiting for a solution

**Comment by hicaoc** [comment]
> encountered the same issue, waiting for a solution
I just tested and changed python to 3.11. This error disappeared, but new problems appeared.

 File "C:\Users\caoc\miniconda3\envs\chattts\Lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caoc\miniconda3\envs\chattts\Lib\site-packages\torch\_inductor\graph.py", line 1254, in compile_to_module
    mod = PyCodeCache.load_by_key_path(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caoc\miniconda3\envs\chattts\Lib\site-packages\torch\_inductor\codecache.py", line 2154, in load_by_key_path
    raise RuntimeError(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Failed to import C:\Users\caoc\AppData\Local\Temp\torchinductor_caoc\hf\chfheta34zg3uml5kkkplxpjtnyriyugrvgccj22bwtkmcqxozdj.py
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 13-14: truncated \UXXXXXXXX escape (chfheta34zg3uml5kkkplxpjtnyriyugrvgccj22bwtkmcqxozdj.py, line 63)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

**Comment by niuroumiantt** [comment]
我也是。 
下载了一键下载到我的电脑里，补充了MODEL 下载，并替换原来的 CONFIG and assets ，RUN , 显示 RuntimeError: Dynamo is not supported on Python 3.12+

**Comment by hicaoc** [comment]
> 我也是。 下载了一键下载到我的电脑里，补充了MODEL 下载，并替换原来的 CONFIG and assets ，RUN , 显示 RuntimeError: Dynamo is not supported on Python 3.12+

用python3.11 先

**Comment by APPX-Studio** [comment]
我用了别的整合包 效果和VITS没什么太大区别 有的字还不读
